apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proj5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: proj5
    spec:
      containers:
      - name: proj5
        image: veereddyt/veerproj5:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: proj5-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: proj5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80