# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

executors:
  docker-publisher:
    environment:
      DOCKER_IMAGE: veereddyt/veerproj5:latest
    docker:
      - image: docker:stable
jobs:
  checkhadolint:
    docker:
# Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
        # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
              make lint 
  build_docker_push:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --tag ${DOCKER_IMAGE} .
      - run:
          name: List docker images
          command: docker image ls
      - run:
          name: Publish Docker image
          command: |
            docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}"
            docker push ${DOCKER_IMAGE}
  deploy-app:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          command: |
            pwd 
            ls -ltra
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: veerclsuter
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/proj5
          show-kubectl-command: true

workflows:
  default:
    jobs:
      - checkhadolint
      - build_docker_push:
          requires: [checkhadolint]
      - deploy-app:
          requires: [build_pushdock]
